### ISSUE TITLE
version-workflow exercise error

### ISSUE THREAD

**Issue by random-bread** [temporalio/edu-102-go-code#6]
**Describe the bug**
ReplayWorkflowHistoryFromJSONFile fails when using the Download functionality with the temporal cli tool

The error is:
```
unknown field "normalName" in taskqueue.TaskQueue
```

**Note**: If you're having issues with the course, or need assistance with the course itself, please post your questions to the support forum at https://community.temporal.io/c/training

**To Reproduce**
2. Clone this repository
3. Run temporal cli (`temporal version 0.10.6 (server 1.22.0) (ui 2.18.2)`
4. Follow Part A in exercises/version-workflow/READEME.md
5. Copy the `TestReplayWorkflowHistoryFromFile` test from solution/workflow_test.go to the practice directory
6. Run the go tests in the practice directory.
7. See error: `unknown field "normalName" in taskqueue.TaskQueue`

**Expected behavior**
Part B of the practice instructions expects the error to be a non-deterministic error.

**Screenshots**
![Screenshot 2023-10-11 at 3 06 49 PM](https://github.com/temporalio/edu-102-go-code/assets/110845525/28484277-457a-419c-bff4-47c1427614fa)

**Desktop (please complete the following information):**
 - OS: macOS 13.4
 - Browser chrome
 - Version 117

**Smartphone (please complete the following information):**
 - N/A
- Are you using Gitpod or developing locally? developing locally

**Additional context**

**Comment by random-bread** [comment]
I fixed the issue for myself by updating the temporal sdk to v1.25.0 in this repository.

**Comment by tomwheeler** [comment]
I sincerely apologize for not seeing and responding to this issue sooner (I'll set up some additional notifications to fix that in the future). This exercise has since been moved to the __Versioning Workflows with Go__ course and I've confirmed that the issue is fixed there (it's using Go SDK v1.26.1, which is the latest one).
